// Generated by CoffeeScript 1.9.2
(function() {
  Background.PageActionDecider = (function() {
    function PageActionDecider(tab) {
      this.tab = tab;
      this.api = new Background.Api;
    }

    PageActionDecider.prototype.decide = function() {
      if (this.is_product_url()) {
        return this.show_page_action();
      } else {
        return this.hide_page_action();
      }
    };

    PageActionDecider.prototype.is_product_url = function() {
      return this.tab.url.match(/^https?:\/\/www.producthunt.com\/posts\//);
    };

    PageActionDecider.prototype.check_authorization = function() {
      return this.api.is_authorized((function(_this) {
        return function(authorized) {
          if (authorized) {
            return _this.check_collection_count();
          } else {
            return _this.show_page_action();
          }
        };
      })(this));
    };

    PageActionDecider.prototype.show_page_action = function() {
      return chrome.pageAction.show(this.tab.id);
    };

    PageActionDecider.prototype.hide_page_action = function() {
      chrome.pageAction.hide(this.tab.id);
      return chrome.storage.sync.set({
        collections: []
      });
    };

    return PageActionDecider;

  })();

}).call(this);
