// Generated by CoffeeScript 1.9.2
(function() {
  window.Api = (function() {
    Api.prototype.api_base = 'https://api.producthunt.com/v1';

    function Api() {
      this.url = window.location.href;
    }

    return Api;

  })();

}).call(this);
