// Generated by CoffeeScript 1.9.2
(function() {
  var Popup,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Popup = (function() {
    function Popup() {
      this.search = bind(this.search, this);
      this.populate();
      this.bind();
    }

    Popup.prototype.populate = function() {
      return this.retrieve_page_id((function(_this) {
        return function(id) {
          return chrome.runtime.getBackgroundPage(function(bg) {
            return bg.get_collections(id, function(collections) {
              var collection, j, len, results;
              $('#waiting').hide();
              $('#collections').show();
              if (collections === 'error') {
                return _this.show_error();
              } else {
                $('#filter').show();
                results = [];
                for (j = 0, len = collections.length; j < len; j++) {
                  collection = collections[j];
                  results.push(_this.add_collection(collection));
                }
                return results;
              }
            });
          });
        };
      })(this));
    };

    Popup.prototype.add_collection = function(collection) {
      var $a, $li;
      $li = $('<li class="collection"></li>').appendTo($('ul#collections'));
      $a = $("<a href='" + collection.collection_url + "'></a>").appendTo($li);
      $("<h2><span class='count'>" + collection.posts_count + "</span> " + collection.name + "</h2>").appendTo($a);
      $("<img src='" + collection.user.image_url['30px'] + "'>").appendTo($a);
      return $("<span class='user_name'>" + collection.user.name + "</span>").appendTo($a);
    };

    Popup.prototype.show_error = function() {
      var $li;
      return $li = $('<li class="collection error"><h2>Sorry, an error occured while contacting product hunt :(</h2></li>').appendTo($('ul#collections'));
    };

    Popup.prototype.bind = function() {
      $('#collections').on('click', 'a', function() {
        return window.open(this.href);
      });
      $('#filter').on('keyup', this.search);
      return $('#filter').on('search', this.search);
    };

    Popup.prototype.search = function() {
      var term;
      term = $('#filter').val().toLowerCase();
      if (term.length === 0) {
        return this.show_all();
      } else {
        $('.collection').each(function(i, el) {
          var $el;
          $el = $(el);
          if ($el.text().toLowerCase().indexOf(term) === -1) {
            return $el.hide();
          } else {
            return $el.show();
          }
        });
        if ($('.collection:visible').length) {
          return this.no_result().hide();
        } else {
          return this.no_result().show();
        }
      }
    };

    Popup.prototype.no_result = function() {
      return this._no_result != null ? this._no_result : this._no_result = $('<li id="no-result">Sorry, no match for that.</li>').appendTo($('#collections'));
    };

    Popup.prototype.show_all = function() {
      return $('.collection').show();
    };

    Popup.prototype.retrieve_page_id = function(callback) {
      return chrome.tabs.query({
        active: true
      }, function(tabs) {
        var tab;
        tab = tabs[0];
        return chrome.tabs.executeScript(tab.id, {
          code: "JSON.parse( document.querySelector( '[data-react-class=\"PostDetailHeader\"]' ).dataset.reactProps ).id"
        }, function(id) {
          if (id) {
            return callback(id);
          }
        });
      });
    };

    return Popup;

  })();

  document.addEventListener('DOMContentLoaded', function() {
    return new Popup();
  });

}).call(this);
